project:
  type: website
  output-dir: docs

website:
  title: "R pour les GeoSentiNum"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - contenu.qmd
      - organisation.qmd
      - DM.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

